const DEFAULT={site:{name:'4 GENTS',youtube:'https://youtube.com/@a.4gents'},news:[],quickUpdates:[{label:'Redeem Codes',text:'Only publish codes you have checked. Codes may expire or have redemption limits.',status:'NEW'},{label:'Events',text:'Add event dates, rewards and a source link when you publish an update.',status:'LIVE'},{label:'Esports',text:'Share match schedules, results and highlights with your readers.',status:'HOT'}]};
let data=JSON.parse(localStorage.getItem('4gents-news-data')||'null')||DEFAULT,selected=null;
const $=id=>document.getElementById(id), fields=['title','category','tag','date','description','content','image','featured'];
function saveLocal(){localStorage.setItem('4gents-news-data',JSON.stringify(data));renderList()}
function clearForm(){selected=null;fields.forEach(k=>$(k).type==='checkbox'?$(k).checked=false:$(k).value='');$('category').value='Free Fire';$('tag').value='NEWS';$('date').value=new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase().replaceAll(' ',' ');$('saveBtn').textContent='Save story'}
function renderList(){const list=$('storyList');$('count').textContent=`${data.news.length} stor${data.news.length===1?'y':'ies'}`;list.innerHTML=data.news.map(n=>`<button class="story-row ${selected===n.id?'active':''}" data-id="${n.id}"><span><b>${escapeHtml(n.title)}</b><small>${escapeHtml(n.category)} • ${escapeHtml(n.date)}</small></span><span>›</span></button>`).join('')||'<p class="muted">No stories yet.</p>';document.querySelectorAll('.story-row').forEach(b=>b.onclick=()=>loadStory(b.dataset.id))}
function escapeHtml(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function loadStory(id){const n=data.news.find(x=>x.id===id);if(!n)return;selected=id;fields.forEach(k=>$(k).type==='checkbox'?$(k).checked=!!n[k]:$(k).value=n[k]||'');$('saveBtn').textContent='Update story';renderList();scrollTo({top:0,behavior:'smooth'})}
$('saveBtn').onclick=()=>{const title=$('title').value.trim();if(!title){alert('Please enter a title.');return}const n={id:selected||('story-'+Date.now()),title,category:$('category').value,tag:$('tag').value.trim()||'NEWS',date:$('date').value.trim()||new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase(),description:$('description').value.trim(),content:$('content').value.trim(),image:$('image').value.trim(),featured:$('featured').checked};if(selected){const i=data.news.findIndex(x=>x.id===selected);data.news[i]=n}else data.news.unshift(n);saveLocal();clearForm();alert('Story saved on this phone. Tap Export news.json when you are ready to publish it.');};
$('deleteBtn').onclick=()=>{if(!selected){alert('Select a story first.');return}if(confirm('Delete this story?')){data.news=data.news.filter(n=>n.id!==selected);saveLocal();clearForm()}};
$('newBtn').onclick=clearForm;
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='news.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('importBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result);if(!Array.isArray(incoming.news))throw Error();data=incoming;saveLocal();clearForm();alert('news.json imported.')}catch{alert('That file is not a valid 4 GENTS news.json.')}};r.readAsText(f)};
clearForm();renderList();
